[package]

name = "c_string"
version = "0.5.2-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]
description = "C string helpers for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"
keywords = ["C", "string"]
repository = "https://github.com/mzabaluev/rust-c-str.git"

[lib]
name = "c_string"
path = "src/c_str.rs"
