[package]

name = "c_string"
version = "0.0.1-pre"
authors = [ "Mikhail Zabaluev <mikhail.zabaluev@gmail.com>" ]

description = "C string helpers for Rust"

readme = "README.md"

keywords = ["C", "string"]

[lib]
name = "c_string"
path = "src/c_str.rs"
